# Generated by Django 4.1.2 on 2022-10-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('sizeX', models.IntegerField()),
                ('sizeY', models.IntegerField()),
                ('obj', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
                ('kategory', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('transfer', models.CharField(max_length=4095)),
            ],
        ),
    ]
