# Generated by Django 4.1.2 on 2022-10-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_obj_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='obj',
            new_name='Galery',
        ),
    ]
