# Generated by Django 4.1.2 on 2022-10-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_rename_obj_galery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='img',
            field=models.ImageField(upload_to='static/image'),
        ),
    ]
