# Generated by Django 4.1.2 on 2022-10-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_alter_galery_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galery',
            old_name='collection',
            new_name='base',
        ),
        migrations.AddField(
            model_name='galery',
            name='dir',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galery',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galery',
            name='material',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
