# Generated by Django 4.1.2 on 2022-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_rename_collection_galery_base_galery_dir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='galery',
            old_name='kategory',
            new_name='category',
        ),
    ]
