# Generated by Django 4.1.2 on 2022-10-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_category_objects_rename_kategory_galery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.category'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.objects'),
        ),
    ]
