# Generated by Django 4.1.2 on 2022-10-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_alter_galery_author_alter_galery_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='base',
        ),
        migrations.RemoveField(
            model_name='galery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='galery',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='galery',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='galery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.category'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='galery',
            name='description',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='galery',
            name='dir',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='galery',
            name='material',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='galery',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='galery',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.objects'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='sizeX',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='galery',
            name='sizeY',
            field=models.IntegerField(),
        ),
    ]
