# Generated by Django 4.1.2 on 2022-10-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_remove_galery_base_remove_galery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.category'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='description',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='dir',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='material',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first.objects'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='sizeX',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='galery',
            name='sizeY',
            field=models.IntegerField(null=True),
        ),
    ]
