# Generated by Django 4.1.2 on 2022-10-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_alter_galery_author_alter_galery_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
