# Generated by Django 4.1.2 on 2022-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='img',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/'),
        ),
    ]
