# Generated by Django 4.1.2 on 2022-10-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_alter_galery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.category'),
        ),
    ]
